name: API tests
description: 'API test suite'
inputs:
  python-version:
    required: false
    default: '3.11'
  
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: |
          tests/requirements.txt
    - name: Install dependencies
      shell: bash
      run: |
        pip install -r tests/requirements.txt
    - name: API tests
      shell: bash
      run: |
        pytest -v -s ./tests/

