name: End to end tests

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
  workflow_dispatch: {}

env:
  AWS_ROLE_ARN: ${{ vars.INTEGRATION_TESTS_INFRA_AWS_ROLE_ARN }}
  AWS_REGION: us-west-2
  PYTHON_VERSION: "3.11"
  LINK_CREATOR_LAMBDA_NAME: dog-api-link-creator
  LINK_RETRIEVER_LAMBDA_NAME: dog-api-link-retriever
  TERRAFORM_ENVIRONMENT_FILE: /tmp/test_terraform_environment

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: End to end tests
    defaults:
      run:
        working-directory: terraform/
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        role-session-name: github-actions
        aws-region: ${{ env.AWS_REGION }}
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9"
    - name: Terraform init
      run: |
        # use local state
        cp fixtures/test_backend.tf backend.tf
        terraform init
    - name: Terraform apply
      id: terraform_apply
      run: |
        terraform apply -var-file=./fixtures/test.tfvars -auto-approve || terraform apply -var-file=./fixtures/test.tfvars -auto-approve
        echo "bucket_name=$(terraform output -raw bucket_name)" >> $GITHUB_OUTPUT
        echo "api_url=$(terraform output -raw api_url)" >> $GITHUB_OUTPUT
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: pip
    - name: Build and test link-creator
      uses: ./.github/actions/link-creator-test-build
      id: link_creator
    - name: Deploy link-creator
      run: |    
        aws lambda update-function-code \
        --function-name ${{ env.LINK_CREATOR_LAMBDA_NAME }} \
        --zip-file fileb://${{ steps.link_creator.outputs.artifact-path }}
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.21'
        cache-dependency-path: "**/*.sum"
    - name: Build and test link-retriever
      uses: ./.github/actions/link-retriever-test-build
      id: link_retriever
      env:
        GOARCH: arm64
    - name: Build and deploy link-retriever
      run: |
        aws lambda update-function-code \
        --function-name ${{ env.LINK_RETRIEVER_LAMBDA_NAME }} \
        --zip-file fileb://${{ steps.link_retriever.outputs.artifact-path }}
    - name: Upload test file
      run: |
        aws s3 cp --recursive ../.github/fixtures/ s3://${{ steps.terraform_apply.outputs.bucket_name }}/upload
    - name: Run API tests
      uses: ./.github/actions/api-tests
      id: api_tests
      env:
        API_URL: ${{ steps.terraform_apply.outputs.api_url }}
    - name: Destroy infra
      if: always()
      run: |
        terraform destroy -var-file=./fixtures/test.tfvars -auto-approve 
